# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailform', '0002_auto_20160526_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
